### ISSUE TITLE
What use case is filterPrefix for?

### ISSUE THREAD

**Issue by robertfausk** [ry167/twig-gravatar#8]
...cause it prevents code completion in PHPStorm.
https://github.com/ry167/twig-gravatar#prefix

no code completion:
 `            new \Twig_SimpleFilter($this->filterPrefix . 'Avatar', array($this, 'avatar'), $this->filterOptions),`

with code completion:
 `            new \Twig_SimpleFilter('grAvatar', array($this, 'avatar'), $this->filterOptions),`

**Comment by ryanhalliday** [comment]
This was so that people could customize the prefix, depending on what they preferred, such as `gravatarAvatar` or just the short `grAvatar`.

A possible change to allow both cases would be to check if `filterPrefix` is not `gr`, then we create using `$this->filterPrefix . 'Avatar'` otherwise we create using `'grAvatar'`. 
Thats a bit messy but I think it covers both cases nicely?

I don't use PHPStorm so this never came up for me sorry

**Comment by robertfausk** [comment]
Sounds good! I'll create a PR for this.
